openapi: 3.0.0
info:
  description: "This file is about the APIs for SEMojo project: a website to provide services of advanced software engineering techniques (automated testing, repairing, code generation, code summarization, etc.)"
  version: "1.0.0"
  title: "Semojo APIs"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "11711621@swagger.io"
  license:
    name: "GPL-3.0 License"
host: "47.102.206.216"

basePath: "semojo/v1"
tags:
- name: "store"
  description: "Access to Petstore orders"
- name: "customer"
  description: "Operations about customer"
  externalDocs:
    description: "github repository read me"
    url: "https://github.com/JasonAchillious/SEMojo"
- name: "contributor"
  description: "Operations about contributor"
- name: "admin"
  description: "Operations about administrator"
schemes:
- "http"

paths:
  /login:
     